# Site settings
title: Ketunmaan - Selk채senkyl채n kyl채yhdistys ry
description: Tervetuloa Ketunmaan kyl채yhdistyksen kotisivuille
baseurl: ""
url: "https://www.ketunmaa.com"

# Remove GitHub links
show_downloads: false
github:
  is_project_page: false

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Language
lang: fi-FI
